<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\WindowsDevInspector.Core\WindowsDevInspector.Core.csproj" />
    <ProjectReference Include="..\WindowsDevInspector.Windows\WindowsDevInspector.Windows.csproj" />
    <ProjectReference Include="..\WindowsDevInspector.Remediation\WindowsDevInspector.Remediation.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
